### ISSUE TITLE
Filtering Cassandra mutations

### ISSUE THREAD

**Issue by rakulkar-tibco** [datastax/cdc-apache-cassandra#106]
Hello,

Is there a way where we can configure to send only selected type of Cassandra mutations(e.g. inserts only) to the pulsar topic?

**Comment by aymkhalil** [comment]
There is no way to do it out of the box. However, depending in your use case, you can leverage pulsar transformations [drop](https://github.com/datastax/pulsar-transformations#drop) step to filter our records post the fact (works with sinks and functions). If you provide more details about your use case we might be able to better help you.

**Comment by rakulkar-tibco** [comment]
We need information about Cassandra insert/update/delete operations on pulsar topics - which is getting addressed with  cdc-apache-cassandra library. But we need to filter elements based on user preference ( i.e. user might want to listen to only insert/updates and not delete).

**Comment by aymkhalil** [comment]
That is fair exceptions. Unfortunately it is not possible to add filtration capability with the current design because the CDC connector relies on a CQL SELECT to retrieve the final state of the record before sending it to the data topic. At this point, it is hard to tell if the modification was an INSERT or UPDATE. DELETE is a bit different as you'd receive a null value on the data topic so more or else some filtration can be done, but it won't be a fully fledged feature.

Having said that, if you have ideas/contribution you'd like to add to this project in this regards, we'd be happy to support you.
